[package]
name = "fry-common"
version = "0.1.0"
edition = "2021"
license = "MIT-Festival"

[dependencies]
lazy-regex = { version = "3.1.0", path = "../../lazy-regex", default-features = false, features = ["regex", "critical-section"] }
